DROP SEQUENCE seq_k_bulkloads;
DROP SEQUENCE seq_k_contact_refs;
DROP SEQUENCE seq_k_welcme_pak;
DROP FUNCTION k_sp_del_sales_man (CHAR);
DROP FUNCTION k_sp_del_contact (CHAR);
DROP FUNCTION k_sp_del_company (CHAR);
DROP FUNCTION k_sp_del_oportunity (CHAR);
DROP FUNCTION k_sp_del_supplier (CHAR);
DROP FUNCTION k_sp_dedup_email_contacts (CHAR);
DROP FUNCTION k_sp_dedup_oportunities ();
DROP FUNCTION k_sp_objetives_for_contact (CHAR);
DROP FUNCTION k_sp_count_oportunities_for_each_contact ();
