package com.knowgate.hipergate.mobile.event;

import com.knowgate.hipergate.mobile.MyOPs;

import org.morfeo.tidmobile.server.RequestData;
import org.morfeo.tidmobile.server.flow.IActionExecutor;

/* Java code was generated by MyMobileWeb Plugin */
public class DefaultEventHandler {


public void lindex_onclick(RequestData req, IActionExecutor act) 
 throws Throwable {
 }

public void lback_onclick(RequestData req, IActionExecutor act) 
 throws Throwable {
 }

}