package com.knowgate.hipergate.mobile;


/* Java code was generated by MyMobileWeb Plugin */
public class MyOPs {

public static final String INITOP = "InitOp";


public static final String LOGIN = "Login";


public static final String MESSAGES = "Messages";



}