package com.knowgate.hipergate.mobile;


/* Java code was generated by MyMobileWeb Plugin */
public class MyPresentations {

public static final String INITOP_INITPR = "initPr";


public static final String LOGIN_LOGIN = "login";


public static final String MESSAGES_ERROR = "error";


public static final String MESSAGES_INFORMATION = "information";


public static final String MESSAGES_PLAIN = "plain";


public static final String MESSAGES_QUESTION = "question";


public static final String MESSAGES_WARNING = "warning";



}